// (C) 2022 StunxFS. All rights reserved. Use of this source code is
// governed by an MIT license that can be found in the LICENSE file.

// File generated by Sted.
// Please, do not edit this file. Your changes may be overwritten.

#ifndef STUGE_CONFIG_H
#define STUGE_CONFIG_H

#define GAME_NAME "stuge"
#define GAME_DEFAULT_WIDTH 870
#define GAME_DEFAULT_HEIGHT 580

#endif // STUGE_CONFIG_H