// File generated by 'tools/asset2c.py'
// Please, do not edit this file. Your changes may be overwritten.

#ifndef STUGE_LANGS_SPANISH_H
#define STUGE_LANGS_SPANISH_H

#define LANGS_SPANISH_SIZE 114

static char LANGS_SPANISH[LANGS_SPANISH_SIZE] = {
	78, 101, 119, 71, 97, 109, 101, 32, 61, 32, 34, 78, 117, 101, 118, 111, 32, 74, 117, 
	101, 103, 111, 34, 10, 79, 112, 116, 105, 111, 110, 115, 32, 61, 32, 34, 
	79, 112, 99, 105, 111, 110, 101, 115, 34, 10, 69, 120, 105, 116, 32, 61, 
	32, 34, 83, 97, 108, 105, 114, 34, 10, 10, 66, 97, 99, 107, 32, 61, 32, 34, 
	82, 101, 103, 114, 101, 115, 97, 114, 34, 10, 10, 71, 97, 109, 101, 76, 97, 
	110, 103, 32, 61, 32, 34, 76, 101, 110, 103, 117, 97, 106, 101, 32, 100, 
	101, 108, 32, 106, 117, 101, 103, 111, 58, 32, 34, 10
};

#endif // STUGE_LANGS_SPANISH_H
