// File generated by 'tools/asset2c.py'
// Please, do not edit this file. Your changes may be overwritten.

#ifndef LANGS_ENGLISH_H
#define LANGS_ENGLISH_H

#define LANGS_ENGLISH_SIZE 70

static char LANGS_ENGLISH[LANGS_ENGLISH_SIZE] = {
	78, 101, 119, 71, 97, 109, 101, 32, 61, 32, 34, 78, 101, 119, 32, 71, 97, 109, 101, 
	34, 10, 79, 112, 116, 105, 111, 110, 115, 32, 61, 32, 34, 79, 112, 116, 105, 
	111, 110, 115, 34, 10, 69, 120, 105, 116, 32, 61, 32, 34, 69, 120, 105, 116, 
	34, 10, 10, 66, 97, 99, 107, 32, 61, 32, 34, 66, 97, 99, 107, 34, 10
};

#endif // LANGS_ENGLISH_H
